package com.http;

import com.google.gson.Gson;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.*;
import org.springframework.stereotype.Service;
import org.springframework.util.MultiValueMap;
import org.springframework.web.client.RestTemplate;

import java.util.Map;

@Service
public class HttpClient {
    private static final Logger logger = LoggerFactory.getLogger(HttpClient.class);

    /**
     * @param url
     * @param method
     * @param params
     * @return // get 请求
     * public <T> T getForObject();
     * public <T> ResponseEntity<T> getForEntity();
     * <p>
     * // head 请求
     * public HttpHeaders headForHeaders();
     * <p>
     * // post 请求
     * public URI postForLocation();
     * public <T> T postForObject();
     * public <T> ResponseEntity<T> postForEntity();
     * <p>
     * // put 请求
     * public void put();
     * <p>
     * // pathch
     * public <T> T patchForObject
     * <p>
     * // delete
     * public void delete()
     * <p>
     * // options
     * public Set<HttpMethod> optionsForAllow
     * <p>
     * // exchange
     * public <T> ResponseEntity<T> exchange()
     */
    public Map client(String url, HttpMethod method, MultiValueMap<String, Object> params) {
        logger.info("请求接口：{}，{}，{}，{}", url, method, params.toString());
        RestTemplate template = new RestTemplate();
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<MultiValueMap> entity = new HttpEntity(params,headers);
        ResponseEntity<Map> exchange = template.exchange(url, method, entity, Map.class);
        return exchange.getBody();
    }

    public Map get(String url) {
        logger.info("请求get接口：{}", url);
        RestTemplate template = new RestTemplate();
        String str= template.getForObject(url, String.class);
        System.err.println("输入内容"+str);
        return new Gson().fromJson(str,Map.class);
    }

    public String post(String url,MultiValueMap<String, Object> params) {
        logger.info("请求post接口：{}", url);
        RestTemplate template = new RestTemplate();
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        HttpEntity<String> formEntity = new HttpEntity<String>(params.toString(), headers);
        ResponseEntity<String> response1 = template.postForEntity(url,formEntity,String.class);
        return response1.getBody();
    }

    public static void main(String[] args) {
        String str[][] = {{"101180107","zhongmou","中牟","zhengzhou","郑州","henan","河南","china","中国"},
                {"101180108","shangjie","上街","zhengzhou","郑州","henan","河南","china","中国"},
                {"101180201","anyang","安阳","anyang","安阳","henan","河南","china","中国"},
                {"101180202","tangyin","汤阴","anyang","安阳","henan","河南","china","中国"},
                {"101180203","huaxian","滑县","anyang","安阳","henan","河南","china","中国"},
                {"101180204","neihuang","内黄","anyang","安阳","henan","河南","china","中国"},
                {"101180205","linzhou","林州","anyang","安阳","henan","河南","china","中国"},
                {"101180301","xinxiang","新乡","xinxiang","新乡","henan","河南","china","中国"},
                {"101180302","huojia","获嘉","xinxiang","新乡","henan","河南","china","中国"},
                {"101180303","yuanyang","原阳","xinxiang","新乡","henan","河南","china","中国"},
                {"101180304","huixian","辉县","xinxiang","新乡","henan","河南","china","中国"},
                {"101180305","weihui","卫辉","xinxiang","新乡","henan","河南","china","中国"},
                {"101180306","yanjin","延津","xinxiang","新乡","henan","河南","china","中国"},
                {"101180307","fengqiu","封丘","xinxiang","新乡","henan","河南","china","中国"},
                {"101180308","changyuan","长垣","xinxiang","新乡","henan","河南","china","中国"},
                {"101180401","xuchang","许昌","xuchang","许昌","henan","河南","china","中国"},
                {"101180402","yanling","鄢陵","xuchang","许昌","henan","河南","china","中国"},
                {"101180403","xiangcheng","襄城","xuchang","许昌","henan","河南","china","中国"},
                {"101180404","changge","长葛","xuchang","许昌","henan","河南","china","中国"},
                {"101180405","yuzhou","禹州","xuchang","许昌","henan","河南","china","中国"},
                {"101180501","pingdingshan","平顶山","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180502","jiaxian","郏县","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180503","baofeng","宝丰","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180504","ruzhou","汝州","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180505","yexian","叶县","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180506","wugang","舞钢","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180507","lushan","鲁山","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180508","shilong","石龙","pingdingshan","平顶山","henan","河南","china","中国"},
                {"101180601","xinyang","信阳","xinyang","信阳","henan","河南","china","中国"},
                {"101180602","xixian","息县","xinyang","信阳","henan","河南","china","中国"},
                {"101180603","luoshan","罗山","xinyang","信阳","henan","河南","china","中国"},
                {"101180604","guangshan","光山","xinyang","信阳","henan","河南","china","中国"},
                {"101180605","xinxian","新县","xinyang","信阳","henan","河南","china","中国"},
                {"101180606","huaibin","淮滨","xinyang","信阳","henan","河南","china","中国"},
                {"101180607","huangchuan","潢川","xinyang","信阳","henan","河南","china","中国"},
                {"101180608","gushi","固始","xinyang","信阳","henan","河南","china","中国"},
                {"101180609","shangcheng","商城","xinyang","信阳","henan","河南","china","中国"},
                {"101180701","nanyang","南阳","nanyang","南阳","henan","河南","china","中国"},
                {"101180702","nanzhao","南召","nanyang","南阳","henan","河南","china","中国"},
                {"101180703","fangcheng","方城","nanyang","南阳","henan","河南","china","中国"},
                {"101180704","sheqi","社旗","nanyang","南阳","henan","河南","china","中国"},
                {"101180705","xixia","西峡","nanyang","南阳","henan","河南","china","中国"},
                {"101180706","neixiang","内乡","nanyang","南阳","henan","河南","china","中国"},
                {"101180707","zhenping","镇平","nanyang","南阳","henan","河南","china","中国"},
                {"101180708","xichuan","淅川","nanyang","南阳","henan","河南","china","中国"},
                {"101180709","xinye","新野","nanyang","南阳","henan","河南","china","中国"},
                {"101180710","tanghe","唐河","nanyang","南阳","henan","河南","china","中国"},
                {"101180711","dengzhou","邓州","nanyang","南阳","henan","河南","china","中国"},
                {"101180712","tongbai","桐柏","nanyang","南阳","henan","河南","china","中国"},
                {"101180801","kaifeng","开封","kaifeng","开封","henan","河南","china","中国"},
                {"101180802","qixian","杞县","kaifeng","开封","henan","河南","china","中国"},
                {"101180803","weishi","尉氏","kaifeng","开封","henan","河南","china","中国"},
                {"101180804","tongxu","通许","kaifeng","开封","henan","河南","china","中国"},
                {"101180805","lankao","兰考","kaifeng","开封","henan","河南","china","中国"},
                {"101180901","luoyang","洛阳","luoyang","洛阳","henan","河南","china","中国"},
                {"101180902","xinan","新安","luoyang","洛阳","henan","河南","china","中国"},
                {"101180903","mengjin","孟津","luoyang","洛阳","henan","河南","china","中国"},
                {"101180904","yiyang","宜阳","luoyang","洛阳","henan","河南","china","中国"},
                {"101180905","luoning","洛宁","luoyang","洛阳","henan","河南","china","中国"},
                {"101180906","yichuan","伊川","luoyang","洛阳","henan","河南","china","中国"},
                {"101180907","songxian","嵩县","luoyang","洛阳","henan","河南","china","中国"},
                {"101180908","yanshi","偃师","luoyang","洛阳","henan","河南","china","中国"},
                {"101180909","luanchuan","栾川","luoyang","洛阳","henan","河南","china","中国"},
                {"101180910","ruyang","汝阳","luoyang","洛阳","henan","河南","china","中国"},
                {"101180911","jili","吉利","luoyang","洛阳","henan","河南","china","中国"},
                {"101181001","shangqiu","商丘","shangqiu","商丘","henan","河南","china","中国"},
                {"101181003","suixian","睢县","shangqiu","商丘","henan","河南","china","中国"},
                {"101181004","minquan","民权","shangqiu","商丘","henan","河南","china","中国"},
                {"101181005","yucheng","虞城","shangqiu","商丘","henan","河南","china","中国"},
                {"101181006","zhecheng","柘城","shangqiu","商丘","henan","河南","china","中国"},
                {"101181007","ningling","宁陵","shangqiu","商丘","henan","河南","china","中国"},
                {"101181008","xiayi","夏邑","shangqiu","商丘","henan","河南","china","中国"},
                {"101181009","yongcheng","永城","shangqiu","商丘","henan","河南","china","中国"},
                {"101181101","jiaozuo","焦作","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181102","xiuwu","修武","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181103","wuzhi","武陟","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181104","qinyang","沁阳","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181106","boai","博爱","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181107","wenxian","温县","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181108","mengzhou","孟州","jiaozuo","焦作","henan","河南","china","中国"},
                {"101181201","hebi","鹤壁","hebi","鹤壁","henan","河南","china","中国"},
                {"101181202","xunxian","浚县","hebi","鹤壁","henan","河南","china","中国"},
                {"101181203","qixian","淇县","hebi","鹤壁","henan","河南","china","中国"},
                {"101181301","puyang","濮阳","puyang","濮阳","henan","河南","china","中国"},
                {"101181302","taiqian","台前","puyang","濮阳","henan","河南","china","中国"},
                {"101181303","nanle","南乐","puyang","濮阳","henan","河南","china","中国"},
                {"101181304","qingfeng","清丰","puyang","濮阳","henan","河南","china","中国"},
                {"101181305","fanxian","范县","puyang","濮阳","henan","河南","china","中国"},
                {"101181401","zhoukou","周口","zhoukou","周口","henan","河南","china","中国"},
                {"101181402","fugou","扶沟","zhoukou","周口","henan","河南","china","中国"},
                {"101181403","taikang","太康","zhoukou","周口","henan","河南","china","中国"},
                {"101181404","huaiyang","淮阳","zhoukou","周口","henan","河南","china","中国"},
                {"101181405","xihua","西华","zhoukou","周口","henan","河南","china","中国"},
                {"101181406","shangshui","商水","zhoukou","周口","henan","河南","china","中国"},
                {"101181407","xiangcheng","项城","zhoukou","周口","henan","河南","china","中国"},
                {"101181408","dancheng","郸城","zhoukou","周口","henan","河南","china","中国"},
                {"101181409","luyi","鹿邑","zhoukou","周口","henan","河南","china","中国"},
                {"101181410","shenqiu","沈丘","zhoukou","周口","henan","河南","china","中国"},
                {"101181501","luohe","漯河","luohe","漯河","henan","河南","china","中国"},
                {"101181502","linying","临颍","luohe","漯河","henan","河南","china","中国"},
                {"101181503","wuyang","舞阳","luohe","漯河","henan","河南","china","中国"},
                {"101181601","zhumadian","驻马店","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181602","xiping","西平","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181603","suiping","遂平","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181604","shangcai","上蔡","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181605","runan","汝南","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181606","biyang","泌阳","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181607","pingyu","平舆","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181608","xincai","新蔡","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181609","queshan","确山","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181610","zhengyang","正阳","zhumadian","驻马店","henan","河南","china","中国"},
                {"101181701","sanmenxia","三门峡","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181702","lingbao","灵宝","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181703","mianchi","渑池","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181704","lushi","卢氏","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181705","yima","义马","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181706","shanxian","陕县","sanmenxia","三门峡","henan","河南","china","中国"},
                {"101181801","jiyuan","济源","jiyuan","济源","henan","河南","china","中国"},
                {"101190101","nanjing","南京","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190102","lishui","溧水","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190103","gaochun","高淳","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190104","jiangning","江宁","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190105","luhe","六合","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190106","jiangpu","江浦","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190107","pukou","浦口","nanjing","南京","jiangsu","江苏","china","中国"},
                {"101190201","wuxi","无锡","wuxi","无锡","jiangsu","江苏","china","中国"},
                {"101190202","jiangyin","江阴","wuxi","无锡","jiangsu","江苏","china","中国"},
                {"101190203","yixing","宜兴","wuxi","无锡","jiangsu","江苏","china","中国"},
                {"101190204","xishan","锡山","wuxi","无锡","jiangsu","江苏","china","中国"},
                {"101190301","zhenjiang","镇江","zhenjiang","镇江","jiangsu","江苏","china","中国"},
                {"101190302","danyang","丹阳","zhenjiang","镇江","jiangsu","江苏","china","中国"},
                {"101190303","yangzhong","扬中","zhenjiang","镇江","jiangsu","江苏","china","中国"},
                {"101190304","jurong","句容","zhenjiang","镇江","jiangsu","江苏","china","中国"},
                {"101190305","dantu","丹徒","zhenjiang","镇江","jiangsu","江苏","china","中国"},
                {"101190401","suzhou","苏州","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190402","changshu","常熟","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190403","zhangjiagang","张家港","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190404","kunshan","昆山","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190405","wuzhong","吴中","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190407","wujiang","吴江","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190408","taicang","太仓","suzhou","苏州","jiangsu","江苏","china","中国"},
                {"101190501","nantong","南通","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190502","haian","海安","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190503","rugao","如皋","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190504","rudong","如东","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190507","qidong","启东","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190508","haimen","海门","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190509","tongzhou","通州","nantong","南通","jiangsu","江苏","china","中国"},
                {"101190601","yangzhou","扬州","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190602","baoying","宝应","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190603","yizheng","仪征","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190604","gaoyou","高邮","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190605","jiangdu","江都","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190606","hanjiang","邗江","yangzhou","扬州","jiangsu","江苏","china","中国"},
                {"101190701","yancheng","盐城","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190702","xiangshui","响水","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190703","binhai","滨海","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190704","funing","阜宁","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190705","sheyang","射阳","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190706","jianhu","建湖","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190707","dongtai","东台","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190708","dafeng","大丰","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190709","yandu","盐都","yancheng","盐城","jiangsu","江苏","china","中国"},
                {"101190801","xuzhou","徐州","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190802","tongshan","铜山","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190803","fengxian","丰县","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190804","peixian","沛县","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190805","pizhou","邳州","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190806","suining","睢宁","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190807","xinyi","新沂","xuzhou","徐州","jiangsu","江苏","china","中国"},
                {"101190901","huaian","淮安","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190902","jinhu","金湖","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190903","xuyi","盱眙","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190904","hongze","洪泽","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190905","lianshui","涟水","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190906","huaiyinqu","淮阴区","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101190908","huaianqu","淮安区","huaian","淮安","jiangsu","江苏","china","中国"},
                {"101191001","lianyungang","连云港","lianyungang","连云港","jiangsu","江苏","china","中国"},
                {"101191002","donghai","东海","lianyungang","连云港","jiangsu","江苏","china","中国"},
                {"101191003","ganyu","赣榆","lianyungang","连云港","jiangsu","江苏","china","中国"},
                {"101191004","guanyun","灌云","lianyungang","连云港","jiangsu","江苏","china","中国"},
                {"101191005","guannan","灌南","lianyungang","连云港","jiangsu","江苏","china","中国"},
                {"101191101","changzhou","常州","changzhou","常州","jiangsu","江苏","china","中国"},
                {"101191102","liyang","溧阳","changzhou","常州","jiangsu","江苏","china","中国"},
                {"101191103","jintan","金坛","changzhou","常州","jiangsu","江苏","china","中国"},
                {"101191104","wujin","武进","changzhou","常州","jiangsu","江苏","china","中国"},
                {"101191201","taizhou","泰州","taizhou","泰州","jiangsu","江苏","china","中国"},
                {"101191202","xinghua","兴化","taizhou","泰州","jiangsu","江苏","china","中国"},
                {"101191203","taixing","泰兴","taizhou","泰州","jiangsu","江苏","china","中国"},
                {"101191204","jiangyan","姜堰","taizhou","泰州","jiangsu","江苏","china","中国"},
                {"101191205","jingjiang","靖江","taizhou","泰州","jiangsu","江苏","china","中国"},
                {"101191301","suqian","宿迁","suqian","宿迁","jiangsu","江苏","china","中国"},
                {"101191302","shuyang","沭阳","suqian","宿迁","jiangsu","江苏","china","中国"},
                {"101191303","siyang","泗阳","suqian","宿迁","jiangsu","江苏","china","中国"},
                {"101191304","sihong","泗洪","suqian","宿迁","jiangsu","江苏","china","中国"},
                {"101191305","suyu","宿豫","suqian","宿迁","jiangsu","江苏","china","中国"},
                {"101200101","wuhan","武汉","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200102","caidian","蔡甸","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200103","huangpi","黄陂","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200104","xinzhou","新洲","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200105","jiangxia","江夏","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200106","dongxihu","东西湖","wuhan","武汉","hubei","湖北","china","中国"},
                {"101200201","xiangyang","襄阳","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200202","xiangzhou","襄州","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200203","baokang","保康","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200204","nanzhang","南漳","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200205","yicheng","宜城","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200206","laohekou","老河口","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200207","gucheng","谷城","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200208","zaoyang","枣阳","xiangyang","襄阳","hubei","湖北","china","中国"},
                {"101200301","ezhou","鄂州","ezhou","鄂州","hubei","湖北","china","中国"},
                {"101200302","liangzihu","梁子湖","ezhou","鄂州","hubei","湖北","china","中国"},
                {"101200401","xiaogan","孝感","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200402","anlu","安陆","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200403","yunmeng","云梦","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200404","dawu","大悟","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200405","yingcheng","应城","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200406","hanchuan","汉川","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200407","xiaochang","孝昌","xiaogan","孝感","hubei","湖北","china","中国"},
                {"101200501","huanggang","黄冈","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200502","hongan","红安","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200503","macheng","麻城","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200504","luotian","罗田","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200505","yingshan","英山","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200506","xishui","浠水","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200507","qichun","蕲春","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200508","huangmei","黄梅","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200509","wuxue","武穴","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200510","tuanfeng","团风","huanggang","黄冈","hubei","湖北","china","中国"},
                {"101200601","huangshi","黄石","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200602","daye","大冶","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200603","yangxin","阳新","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200604","tieshan","铁山","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200605","xialu","下陆","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200606","xisaishan","西塞山","huangshi","黄石","hubei","湖北","china","中国"},
                {"101200701","xianning","咸宁","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200702","chibi","赤壁","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200703","jiayu","嘉鱼","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200704","chongyang","崇阳","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200705","tongcheng","通城","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200706","tongshan","通山","xianning","咸宁","hubei","湖北","china","中国"},
                {"101200801","jingzhou","荆州","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200802","jiangling","江陵","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200803","gongan","公安","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200804","shishou","石首","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200805","jianli","监利","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200806","honghu","洪湖","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200807","songzi","松滋","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101200901","yichang","宜昌","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200902","yuanan","远安","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200903","zigui","秭归","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200904","xingshan","兴山","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200906","wufeng","五峰","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200907","dangyang","当阳","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200908","changyang","长阳","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200909","yidu","宜都","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200910","zhijiang","枝江","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200911","sanxia","三峡","yichang","宜昌","hubei","湖北","china","中国"},
                {"101200912","yiling","夷陵","yichang","宜昌","hubei","湖北","china","中国"},
                {"101201001","enshi","恩施","enshi","恩施","hubei","湖北","china","中国"},
                {"101201002","lichuan","利川","enshi","恩施","hubei","湖北","china","中国"},
                {"101201003","jianshi","建始","enshi","恩施","hubei","湖北","china","中国"},
                {"101201004","xianfeng","咸丰","enshi","恩施","hubei","湖北","china","中国"},
                {"101201005","xuanen","宣恩","enshi","恩施","hubei","湖北","china","中国"},
                {"101201006","hefeng","鹤峰","enshi","恩施","hubei","湖北","china","中国"},
                {"101201007","laifeng","来凤","enshi","恩施","hubei","湖北","china","中国"},
                {"101201008","badong","巴东","enshi","恩施","hubei","湖北","china","中国"},
                {"101201101","shiyan","十堰","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201102","zhuxi","竹溪","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201103","yunxi","郧西","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201104","yunxian","郧县","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201105","zhushan","竹山","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201106","fangxian","房县","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201107","danjiangkou","丹江口","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201108","maojian","茅箭","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201109","zhangwan","张湾","shiyan","十堰","hubei","湖北","china","中国"},
                {"101201201","shennongjia","神农架","shennongjia","神农架","hubei","湖北","china","中国"},
                {"101201301","suizhou","随州","suizhou","随州","hubei","湖北","china","中国"},
                {"101201302","guangshui","广水","suizhou","随州","hubei","湖北","china","中国"},
                {"101201401","jingmen","荆门","jingmen","荆门","hubei","湖北","china","中国"},
                {"101201402","zhongxiang","钟祥","jingmen","荆门","hubei","湖北","china","中国"},
                {"101201403","jingshan","京山","jingmen","荆门","hubei","湖北","china","中国"},
                {"101201404","duodao","掇刀","jingmen","荆门","hubei","湖北","china","中国"},
                {"101201405","shayang","沙洋","jingmen","荆门","hubei","湖北","china","中国"},
                {"101201406","shashi","沙市","jingzhou","荆州","hubei","湖北","china","中国"},
                {"101201501","tianmen","天门","tianmen","天门","hubei","湖北","china","中国"},
                {"101201601","xiantao","仙桃","xiantao","仙桃","hubei","湖北","china","中国"},
                {"101201701","qianjiang","潜江","qianjiang","潜江","hubei","湖北","china","中国"},
                {"101210101","hangzhou","杭州","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210102","xiaoshan","萧山","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210103","tonglu","桐庐","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210104","chunan","淳安","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210105","jiande","建德","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210106","yuhang","余杭","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210107","linan","临安","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210108","fuyang","富阳","hangzhou","杭州","zhejiang","浙江","china","中国"},
                {"101210201","huzhou","湖州","huzhou","湖州","zhejiang","浙江","china","中国"},
                {"101210202","changxing","长兴","huzhou","湖州","zhejiang","浙江","china","中国"},
                {"101210203","anji","安吉","huzhou","湖州","zhejiang","浙江","china","中国"},
                {"101210204","deqing","德清","huzhou","湖州","zhejiang","浙江","china","中国"},
                {"101210301","jiaxing","嘉兴","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210302","jiashan","嘉善","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210303","haining","海宁","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210304","tongxiang","桐乡","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210305","pinghu","平湖","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210306","haiyan","海盐","jiaxing","嘉兴","zhejiang","浙江","china","中国"},
                {"101210401","ningbo","宁波","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210403","cixi","慈溪","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210404","yuyao","余姚","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210405","fenghua","奉化","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210406","xiangshan","象山","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210408","ninghai","宁海","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210410","beilun","北仑","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210411","yinzhou","鄞州","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210412","zhenhai","镇海","ningbo","宁波","zhejiang","浙江","china","中国"},
                {"101210501","shaoxing","绍兴","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210502","zhuji","诸暨","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210503","shangyu","上虞","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210504","xinchang","新昌","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210505","shengzhou","嵊州","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210506","keqiao","柯桥","shaoxing","绍兴","zhejiang","浙江","china","中国"},
                {"101210601","taizhou","台州","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210603","yuhuan","玉环","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210604","sanmen","三门","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210605","tiantai","天台","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210606","xianju","仙居","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210607","wenling","温岭","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210609","hongjia","洪家","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210610","linhai","临海","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210611","jiaojiang","椒江","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210612","huangyan","黄岩","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210613","luqiao","路桥","taizhou","台州","zhejiang","浙江","china","中国"},
                {"101210701","wenzhou","温州","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210702","taishun","泰顺","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210703","wencheng","文成","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210704","pingyang","平阳","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210705","ruian","瑞安","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210706","dongtou","洞头","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210707","yueqing","乐清","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210708","yongjia","永嘉","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210709","cangnan","苍南","wenzhou","温州","zhejiang","浙江","china","中国"},
                {"101210801","lishui","丽水","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210802","suichang","遂昌","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210803","longquan","龙泉","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210804","jinyun","缙云","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210805","qingtian","青田","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210806","yunhe","云和","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210807","qingyuan","庆元","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210808","songyang","松阳","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210809","jingning","景宁","lishui","丽水","zhejiang","浙江","china","中国"},
                {"101210901","jinhua","金华","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210902","pujiang","浦江","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210903","lanxi","兰溪","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210904","yiwu","义乌","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210905","dongyang","东阳","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210906","wuyi","武义","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210907","yongkang","永康","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101210908","panan","磐安","jinhua","金华","zhejiang","浙江","china","中国"},
                {"101211001","quzhou","衢州","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211002","changshan","常山","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211003","kaihua","开化","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211004","longyou","龙游","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211005","jiangshan","江山","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211006","qujiang","衢江","quzhou","衢州","zhejiang","浙江","china","中国"},
                {"101211101","zhoushan","舟山","zhoushan","舟山","zhejiang","浙江","china","中国"},
                {"101211102","shengsi","嵊泗","zhoushan","舟山","zhejiang","浙江","china","中国"},
                {"101211104","daishan","岱山","zhoushan","舟山","zhejiang","浙江","china","中国"},
                {"101211105","putuo","普陀","zhoushan","舟山","zhejiang","浙江","china","中国"},
                {"101211106","dinghai","定海","zhoushan","舟山","zhejiang","浙江","china","中国"},
                {"101220101","hefei","合肥","hefei","合肥","anhui","安徽","china","中国"},
                {"101220102","changfeng","长丰","hefei","合肥","anhui","安徽","china","中国"},
                {"101220103","feidong","肥东","hefei","合肥","anhui","安徽","china","中国"},
                {"101220104","feixi","肥西","hefei","合肥","anhui","安徽","china","中国"},
                {"101220105","chaohu","巢湖","hefei","合肥","anhui","安徽","china","中国"},
                {"101220106","lujiang","庐江","hefei","合肥","anhui","安徽","china","中国"},
                {"101220201","bengbu","蚌埠","bengbu","蚌埠","anhui","安徽","china","中国"},
                {"101220202","huaiyuan","怀远","bengbu","蚌埠","anhui","安徽","china","中国"},
                {"101220203","guzhen","固镇","bengbu","蚌埠","anhui","安徽","china","中国"},
                {"101220204","wuhe","五河","bengbu","蚌埠","anhui","安徽","china","中国"},
                {"101220301","wuhu","芜湖","wuhu","芜湖","anhui","安徽","china","中国"},
                {"101220302","fanyang","繁昌","wuhu","芜湖","anhui","安徽","china","中国"},
                {"101220303","wuhuxian","芜湖县","wuhu","芜湖","anhui","安徽","china","中国"},
                {"101220304","nanling","南陵","wuhu","芜湖","anhui","安徽","china","中国"},
                {"101220305","wuwei","无为","wuhu","芜湖","anhui","安徽","china","中国"},
                {"101220401","huainan","淮南","huainan","淮南","anhui","安徽","china","中国"},
                {"101220402","fengtai","凤台","huainan","淮南","anhui","安徽","china","中国"},
                {"101220403","panji","潘集","huainan","淮南","anhui","安徽","china","中国"},
                {"101220501","maanshan","马鞍山","maanshan","马鞍山","anhui","安徽","china","中国"},
                {"101220502","dangtu","当涂","maanshan","马鞍山","anhui","安徽","china","中国"},
                {"101220503","hanshan","含山","maanshan","马鞍山","anhui","安徽","china","中国"},
                {"101220504","hexian","和县","maanshan","马鞍山","anhui","安徽","china","中国"},
                {"101220601","anqing","安庆","anqing","安庆","anhui","安徽","china","中国"},
                {"101220602","zongyang","枞阳","anqing","安庆","anhui","安徽","china","中国"},
                {"101220603","taihu","太湖","anqing","安庆","anhui","安徽","china","中国"},
                {"101220604","qianshan","潜山","anqing","安庆","anhui","安徽","china","中国"},
                {"101220605","huaining","怀宁","anqing","安庆","anhui","安徽","china","中国"},
                {"101220606","susong","宿松","anqing","安庆","anhui","安徽","china","中国"},
                {"101220607","wangjiang","望江","anqing","安庆","anhui","安徽","china","中国"},
                {"101220608","yuexi","岳西","anqing","安庆","anhui","安徽","china","中国"},
                {"101220609","tongcheng","桐城","anqing","安庆","anhui","安徽","china","中国"},
                {"101220701","suzhou","宿州","suzhou","宿州","anhui","安徽","china","中国"},
                {"101220702","dangshan","砀山","suzhou","宿州","anhui","安徽","china","中国"},
                {"101220703","lingbi","灵璧","suzhou","宿州","anhui","安徽","china","中国"},
                {"101220704","sixian","泗县","suzhou","宿州","anhui","安徽","china","中国"},
                {"101220705","xiaoxian","萧县","suzhou","宿州","anhui","安徽","china","中国"},
                {"101220801","fuyang","阜阳","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220802","funan","阜南","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220803","yingshang","颍上","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220804","linquan","临泉","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220805","jieshou","界首","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220806","taihe","太和","fuyang","阜阳","anhui","安徽","china","中国"},
                {"101220901","bozhou","亳州","bozhou","亳州","anhui","安徽","china","中国"},
                {"101220902","guoyang","涡阳","bozhou","亳州","anhui","安徽","china","中国"},
                {"101220903","lixin","利辛","bozhou","亳州","anhui","安徽","china","中国"},
                {"101220904","mengcheng","蒙城","bozhou","亳州","anhui","安徽","china","中国"},
                {"101221001","huangshan","黄山","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221002","huangshanqu","黄山区","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221003","tunxi","屯溪","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221004","qimen","祁门","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221005","yixian","黟县","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221006","shexian","歙县","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221007","xiuning","休宁","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221008","huangshanfengjingqu","黄山风景区","huangshan","黄山","anhui","安徽","china","中国"},
                {"101221101","chuzhou","滁州","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221102","fengyang","凤阳","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221103","mingguang","明光","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221104","dingyuan","定远","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221105","quanjiao","全椒","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221106","laian","来安","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221107","tianchang","天长","chuzhou","滁州","anhui","安徽","china","中国"},
                {"101221201","huaibei","淮北","huaibei","淮北","anhui","安徽","china","中国"},
                {"101221202","suixi","濉溪","huaibei","淮北","anhui","安徽","china","中国"},
                {"101221301","tongling","铜陵","tongling","铜陵","anhui","安徽","china","中国"},
                {"101221401","xuancheng","宣城","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221402","jingxian","泾县","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221403","jingde","旌德","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221404","ningguo","宁国","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221405","jixi","绩溪","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221406","guangde","广德","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221407","langxi","郎溪","xuancheng","宣城","anhui","安徽","china","中国"},
                {"101221501","luan","六安","luan","六安","anhui","安徽","china","中国"},
                {"101221502","huoqiu","霍邱","liuan","六安","anhui","安徽","china","中国"},
                {"101221503","shouxian","寿县","liuan","六安","anhui","安徽","china","中国"},
                {"101221505","jinzhai","金寨","liuan","六安","anhui","安徽","china","中国"},
                {"101221506","huoshan","霍山","liuan","六安","anhui","安徽","china","中国"},
                {"101221507","shucheng","舒城","liuan","六安","anhui","安徽","china","中国"},
                {"101221701","chizhou","池州","chizhou","池州","anhui","安徽","china","中国"},
                {"101221702","dongzhi","东至","chizhou","池州","anhui","安徽","china","中国"},
                {"101221703","qingyang","青阳","chizhou","池州","anhui","安徽","china","中国"},
                {"101221704","jiuhuashan","九华山","chizhou","池州","anhui","安徽","china","中国"},
                {"101221705","shitai","石台","chizhou","池州","anhui","安徽","china","中国"},
                {"101230101","fuzhou","福州","fuzhou","福州","fujian","福建","china","中国"},
                {"101230102","minqing","闽清","fuzhou","福州","fujian","福建","china","中国"},
                {"101230103","minhou","闽侯","fuzhou","福州","fujian","福建","china","中国"},
                {"101230104","luoyuan","罗源","fuzhou","福州","fujian","福建","china","中国"},
                {"101230105","lianjiang","连江","fuzhou","福州","fujian","福建","china","中国"},
                {"101230107","yongtai","永泰","fuzhou","福州","fujian","福建","china","中国"},
                {"101230108","pingtan","平潭","fuzhou","福州","fujian","福建","china","中国"},
                {"101230110","changle","长乐","fuzhou","福州","fujian","福建","china","中国"},
                {"101230111","fuqing","福清","fuzhou","福州","fujian","福建","china","中国"},
                {"101230201","xiamen","厦门","xiamen","厦门","fujian","福建","china","中国"},
                {"101230202","tongan","同安","xiamen","厦门","fujian","福建","china","中国"},
                {"101230301","ningde","宁德","ningde","宁德","fujian","福建","china","中国"},
                {"101230302","gutian","古田","ningde","宁德","fujian","福建","china","中国"},
                {"101230303","xiapu","霞浦","ningde","宁德","fujian","福建","china","中国"},
                {"101230304","shouning","寿宁","ningde","宁德","fujian","福建","china","中国"},
                {"101230305","zhouning","周宁","ningde","宁德","fujian","福建","china","中国"},
                {"101230306","fuan","福安","ningde","宁德","fujian","福建","china","中国"},
                {"101230307","zherong","柘荣","ningde","宁德","fujian","福建","china","中国"},
                {"101230308","fuding","福鼎","ningde","宁德","fujian","福建","china","中国"},
                {"101230309","pingnan","屏南","ningde","宁德","fujian","福建","china","中国"},
                {"101230401","putian","莆田","putian","莆田","fujian","福建","china","中国"},
                {"101230402","xianyou","仙游","putian","莆田","fujian","福建","china","中国"},
                {"101230403","xiuyugang","秀屿港","putian","莆田","fujian","福建","china","中国"},
                {"101230404","hanjiang","涵江","putian","莆田","fujian","福建","china","中国"},
                {"101230405","xiuyu","秀屿","putian","莆田","fujian","福建","china","中国"},
                {"101230406","licheng","荔城","putian","莆田","fujian","福建","china","中国"},
                {"101230407","chengxiang","城厢","putian","莆田","fujian","福建","china","中国"},
                {"101230501","quanzhou","泉州","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230502","anxi","安溪","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230504","yongchun","永春","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230505","dehua","德化","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230506","nanan","南安","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230507","chongwu","崇武","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230508","huian","惠安","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230509","jinjiang","晋江","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230510","shishi","石狮","quanzhou","泉州","fujian","福建","china","中国"},
                {"101230601","zhangzhou","漳州","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230602","changtai","长泰","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230603","nanjing","南靖","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230604","pinghe","平和","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230605","longhai","龙海","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230606","zhangpu","漳浦","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230607","zhaoan","诏安","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230608","dongshan","东山","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230609","yunxiao","云霄","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230610","huaan","华安","zhangzhou","漳州","fujian","福建","china","中国"},
                {"101230701","longyan","龙岩","longyan","龙岩","fujian","福建","china","中国"},
                {"101230702","changting","长汀","longyan","龙岩","fujian","福建","china","中国"},
                {"101230703","liancheng","连城","longyan","龙岩","fujian","福建","china","中国"},
                {"101230704","wuping","武平","longyan","龙岩","fujian","福建","china","中国"},
                {"101230705","shanghang","上杭","longyan","龙岩","fujian","福建","china","中国"},
                {"101230706","yongding","永定","longyan","龙岩","fujian","福建","china","中国"},
                {"101230707","zhangping","漳平","longyan","龙岩","fujian","福建","china","中国"},
                {"101230801","sanming","三明","sanming","三明","fujian","福建","china","中国"},
                {"101230802","ninghua","宁化","sanming","三明","fujian","福建","china","中国"},
                {"101230803","qingliu","清流","sanming","三明","fujian","福建","china","中国"},
                {"101230804","taining","泰宁","sanming","三明","fujian","福建","china","中国"},
                {"101230805","jiangle","将乐","sanming","三明","fujian","福建","china","中国"},
                {"101230806","jianning","建宁","sanming","三明","fujian","福建","china","中国"},
                {"101230807","mingxi","明溪","sanming","三明","fujian","福建","china","中国"},
                {"101230808","shaxian","沙县","sanming","三明","fujian","福建","china","中国"},
                {"101230809","youxi","尤溪","sanming","三明","fujian","福建","china","中国"},
                {"101230810","yongan","永安","sanming","三明","fujian","福建","china","中国"},
                {"101230811","datian","大田","sanming","三明","fujian","福建","china","中国"},
                {"101230901","nanping","南平","nanping","南平","fujian","福建","china","中国"},
                {"101230902","shunchang","顺昌","nanping","南平","fujian","福建","china","中国"},
                {"101230903","guangze","光泽","nanping","南平","fujian","福建","china","中国"},
                {"101230904","shaowu","邵武","nanping","南平","fujian","福建","china","中国"},
                {"101230905","wuyishan","武夷山","nanping","南平","fujian","福建","china","中国"},
                {"101230906","pucheng","浦城","nanping","南平","fujian","福建","china","中国"},
                {"101230907","jianyang","建阳","nanping","南平","fujian","福建","china","中国"},
                {"101230908","songxi","松溪","nanping","南平","fujian","福建","china","中国"},
                {"101230909","zhenghe","政和","nanping","南平","fujian","福建","china","中国"},
                {"101230910","jianou","建瓯","nanping","南平","fujian","福建","china","中国"},
                {"101231001","diaoyudao","钓鱼岛","diaoyudao","钓鱼岛","fujian","福建","china","中国"},
                {"101240101","nanchang","南昌","nanchang","南昌","jiangxi","江西","china","中国"},
                {"101240102","xinjian","新建","nanchang","南昌","jiangxi","江西","china","中国"},
                {"101240103","nanchangxian","南昌县","nanchang","南昌","jiangxi","江西","china","中国"},
                {"101240104","anyi","安义","nanchang","南昌","jiangxi","江西","china","中国"},
                {"101240105","jinxian","进贤","nanchang","南昌","jiangxi","江西","china","中国"},
                {"101240201","jiujiang","九江","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240202","ruichang","瑞昌","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240203","lushan","庐山","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240204","wuning","武宁","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240205","dean","德安","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240206","yongxiu","永修","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240207","hukou","湖口","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240208","pengze","彭泽","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240209","xingzi","星子","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240210","duchang","都昌","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240212","xiushui","修水","jiujiang","九江","jiangxi","江西","china","中国"},
                {"101240301","shangrao","上饶","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240302","poyang","鄱阳","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240303","wuyuan","婺源","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240305","yugan","余干","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240306","wannian","万年","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240307","dexing","德兴","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240308","shangraoxian","上饶县","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240309","yiyang","弋阳","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240310","hengfeng","横峰","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240311","yanshan","铅山","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240312","yushan","玉山","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240313","guangfeng","广丰","shangrao","上饶","jiangxi","江西","china","中国"},
                {"101240401","fuzhou","抚州","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240402","guangchang","广昌","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240403","anle","乐安","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240404","chongren","崇仁","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240405","jinxi","金溪","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240406","zixi","资溪","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240407","yihuang","宜黄","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240408","nancheng","南城","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240409","nanfeng","南丰","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240410","lichuan","黎川","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240411","dongxiang","东乡","fuzhou","抚州","jiangxi","江西","china","中国"},
                {"101240501","yichun","宜春","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240502","tonggu","铜鼓","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240503","yifeng","宜丰","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240504","wanzai","万载","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240505","shanggao","上高","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240506","jingan","靖安","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240507","fengxin","奉新","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240508","gaoan","高安","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240509","zhangshu","樟树","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240510","fengcheng","丰城","yichun","宜春","jiangxi","江西","china","中国"},
                {"101240601","jian","吉安","jian","吉安","jiangxi","江西","china","中国"},
                {"101240602","jianxian","吉安县","jian","吉安","jiangxi","江西","china","中国"},
                {"101240603","jishui","吉水","jian","吉安","jiangxi","江西","china","中国"},
                {"101240604","xingan","新干","jian","吉安","jiangxi","江西","china","中国"},
                {"101240605","xiajiang","峡江","jian","吉安","jiangxi","江西","china","中国"},
                {"101240606","yongfeng","永丰","jian","吉安","jiangxi","江西","china","中国"},
                {"101240607","yongxin","永新","jian","吉安","jiangxi","江西","china","中国"},
                {"101240608","jinggangshan","井冈山","jian","吉安","jiangxi","江西","china","中国"},
                {"101240609","wanan","万安","jian","吉安","jiangxi","江西","china","中国"},
                {"101240610","suichuan","遂川","jian","吉安","jiangxi","江西","china","中国"},
                {"101240611","taihe","泰和","jian","吉安","jiangxi","江西","china","中国"},
                {"101240612","anfu","安福","jian","吉安","jiangxi","江西","china","中国"},
                {"101240613","ninggang","宁冈","jian","吉安","jiangxi","江西","china","中国"},
                {"101240701","ganzhou","赣州","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240702","chongyi","崇义","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240703","shangyou","上犹","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240704","nankang","南康","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240705","dayu","大余","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240706","xinfeng","信丰","ganzhou","赣州","jiangxi","江西","china","中国"},
                {"101240707","ningdu","宁都","ganzhou","赣州","jiangxi","江西","china","中国"}

        };
        for (String[] s : str){
            System.err.print(s[2]+"(\"");
            for(String s1 : s){
                System.err.print(s1+"\",\"");
            }
            System.err.print("),");
            System.err.println();
        }

    }
}
